POST http://localhost:8080/registration
Content-Type:application/x-www-form-urlencoded

name=Emily&lastname=Clark&login=emilyclark&password=ClarkPassword321

###

POST http://localhost:8080/authorization
Content-Type:application/x-www-form-urlencoded

login=johndoe&password=Password123

###

POST http://localhost:8080/authorization
Content-Type:application/x-www-form-urlencoded

login=admin&password=adminPass

###

POST http://localhost:8080/authorization
Content-Type:application/x-www-form-urlencoded

login=adminLogin&password=adminPassword

###

POST http://localhost:8080/logout

###

GET http://localhost:8080/posts?post-id=11

###

GET http://localhost:8080/posts

###

POST http://localhost:8080/posts
Content-Type:text/plain

My bloody rhythm of the sun — fuck the guns
Fuck the criminal, fuck the screaming gangs
Some people waiting for my sound, let me proud
Ima freeman, Ima woah-woah-woah-woah-woah
My bloody rhythm of the sun — fuck the guns
Fuck the criminal, fuck the screaming gangs
Some people waiting for my sound, let me proud
Ima freeman, Ima woah-woah-woah-woah-woah

###

PUT http://localhost:8080/posts
Content-Type:text/plain

post-id=16&text=This is my first post in switter!

###

POST http://localhost:8080/comments
Content-Type:application/x-www-form-urlencoded

post-id=11&text=Good Track!

###

POST http://localhost:8080/likes
Content-Type:application/x-www-form-urlencoded

post-id=14

