POST http://localhost:8080/registration
Content-Type:application/x-www-form-urlencoded

name=testName&lastname=testLastname&login=testLogin&password=testPassword

###

POST http://localhost:8080/authorization
Content-Type:application/x-www-form-urlencoded

login=testLogin&password=testPassword

###

POST http://localhost:8080/logout

###

GET http://localhost:8080/post?id=11

###

POST http://localhost:8080/post
Content-Type:text/plain

My bloody rhythm of the sun — fuck the guns
Fuck the criminal, fuck the screaming gangs
Some people waiting for my sound, let me proud
Ima freeman, Ima woah-woah-woah-woah-woah
My bloody rhythm of the sun — fuck the guns
Fuck the criminal, fuck the screaming gangs
Some people waiting for my sound, let me proud
Ima freeman, Ima woah-woah-woah-woah-woah
